---
kind: source
spec:
  name: "ns1"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ['file']
  spec:
    apiKey: '1234'
---
kind: destination
spec:
  name: "file"
  path: "cloudquery/file"
  version: "v3.4.6"
  spec:
    path: "data/{{TABLE}}/{{UUID}}.{{FORMAT}}"
    format: "csv"
